/**
 * Shape of src/data/dashboard.json.
 *
 * The JSON is generated by scripts/build-data.ts from ../Spreadsheets/*.xlsx
 * and is the only data source the app reads at runtime. All money values are
 * whole US dollars (the corporate workbooks' "in thousands" figures are
 * scaled up by the build script).
 */

export type ValueFormat = 'usd' | 'pct' | 'signedPct' | 'count';

export interface Kpi {
  label: string;
  value: number;
  format: ValueFormat;
  sub: string;
}

/** One point on a trend line. `forecast` marks a budget/projection point. */
export interface TrendPoint {
  label: string;
  value: number;
  forecast?: boolean;
}

export interface BarItem {
  label: string;
  value: number;
}

export interface StackSeries {
  name: string;
  values: number[];
}

export interface StackChartData {
  categories: string[];
  series: StackSeries[];
}

export interface FinancialPerformance {
  note: string;
  grossRevenue: TrendPoint[];
  netIncome: TrendPoint[];
  /** Percentages, e.g. 62.2 for 62.2%. */
  grossMargin: TrendPoint[];
}

export interface BalanceSheetComposition {
  note: string;
  assets: StackChartData;
  liabilitiesEquity: StackChartData;
}

export interface ExpenseBreakdown {
  year: string;
  note: string;
  labor: BarItem[];
  marketing: BarItem[];
  overhead: BarItem[];
}

export interface EcommercePerformance {
  note: string;
  orders: number;
  revenue: number;
  periodStart: string;
  periodEnd: string;
  byRegion: BarItem[];
  byCategory: BarItem[];
  byChannel: BarItem[];
  topReps: BarItem[];
}

export interface ProductCatalog {
  note: string;
  productCount: number;
  topProducts: BarItem[];
}

export interface DashboardData {
  /** Last-modified time of the newest source workbook (ISO 8601). */
  dataUpdatedAt: string;
  subtitle: string;
  kpis: Kpi[];
  financialPerformance: FinancialPerformance;
  balanceSheet: BalanceSheetComposition;
  expenses: ExpenseBreakdown;
  ecommerce: EcommercePerformance;
  productCatalog: ProductCatalog;
  dataNotes: string[];
}
